#!/usr/bin/env php
<?php
/**
 * @package wallend/newman-php-coverager CLI script
 */

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_INSTALLATION', $file);

        break;
    }
}

unset($file);

if (!defined('COMPOSER_INSTALLATION')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require COMPOSER_INSTALLATION;

if (in_array('--clear-data', $argv)) {
    $path = $argv[array_search('--clear-data', $argv) + 1];

    if (is_dir($path)) {
        array_map(
            function ($file) {
                if (is_file($file)) {
                    unlink($file);
                }
            },
            glob($path . "/*")
        );
    }

    echo "Reports has been cleared...";

    die(0);
}

if (in_array('--collect-reports', $argv)) {
    unset($argv[array_search('--collect-reports', $argv)]);

    $_SERVER['argv'] = $argv;
    $application     = new SebastianBergmann\PHPCOV\Application;

    $application->run();
}